name: deployment
on:
  workflow_run:
    workflows: ["publish"]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Preview Deployment
    runs-on: ubuntu-latest
    environment: preview
    steps:
    - name: ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: ${{ vars.DEPLOY_SCRIPT }}
