name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: preview
    steps:
    - name: ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: ${{ vars.DEPLOY_SCRIPT }}
